### ISSUE TITLE
LESS data-uri() doesn't work

### ISSUE THREAD

**Issue by raphaelgoetter** [jdiehl/brackets-less-autocompile#47]
Hello,

I tried the LESS 1.40 [`data-uri()`](http://lesscss.org/functions/#misc-functions-data-uri) function : `background: data-uri('illust/fromage.gif');`

... but Less autocompile fails on compile :/

**Comment by raphaelgoetter** [comment]
Hello,

Actually, it still doesn't compile to inline images.

input : 

```css
p {
	background-image: data-uri('cat.jpg');
}
```

output : 

```css
p {
  background-image: url('cat.jpg');
}
```

> /* Generated by less 2.4.0 */
