### ISSUE TITLE
percentage function don't work

### ISSUE THREAD

**Issue by powange** [jdiehl/brackets-less-autocompile#55]
``` less
@nb: 7;
.item {
  width: percentage(1/@nb);
}
```

generate 

``` css
.item {
  width: NaN%;
}
```
